### Obtener todas las temporadas
GET http://localhost:3000/api/v1/seasons

### Obtener una temporada por id
GET http://localhost:3000/api/v1/seasons/d2345678-8def-1234-5678-abc456789abc

### Obtener una temporada por id inexistente
GET http://localhost:3000/api/v1/seasons/66afafeb-536e-41e2-8079-2c0b27b7a56b

### Obtener una temporada por id erronea
GET http://localhost:3000/api/v1/seasons/23


### Obtener todas las temporadas por id del cultivo
GET http://localhost:3000/api/v1/crops/328ef414-c70e-4266-a92b-7137219302eb/seasons

### Obtener todas las temporadas por id del cultivo inexistente
GET http://localhost:3000/api/v1/crop/c1234567-9abc-1234-5688-abc456789def/seasons

### Obtener todas las temporadas por id del cultivo erroneo
GET http://localhost:3000/api/v1/crop/c12/seasons

### crear una temporada
POST http://localhost:3000/api/v1/seasons
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}
### crear una temporada sin algunos datos
POST http://localhost:3000/api/v1/seasons
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024",
    "duracion": 120,
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}

### crear una temporada sin datos
POST http://localhost:3000/api/v1/seasons
Content-Type: application/json


### Eliminar una temporada por id
DELETE http://localhost:3000/api/v1/seasons/77217c0b-0cbd-4d4d-a399-2514a4935233

### Actualizar una temporada por id
PATCH http://localhost:3000/api/v1/seasons/7f972af8-cd33-49e8-8340-87cc37ef3876
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024 modificado",
    "duracion": 150
}

### Actualizar una temporada por id
PATCH http://localhost:3000/api/v1/seasons/7f972af8-cd33-49e8-8340-87cc37ef3876
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024 modificado de nuevo",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}
### Actualizar una temporada por id inexistente
PATCH http://localhost:3000/api/v1/seasons/7f972af8-cd33-49e8-8340-87cc37df3876
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024 modificado de nuevo",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}

### Actualizar una temporada por id erronea
PATCH http://localhost:3000/api/v1/seasons/7f
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024 modificado de nuevo",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}

### Modificar una temporada por id
PUT http://localhost:3000/api/v1/seasons/7f972af8-cd33-49e8-8340-87cc37ef3876
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}
### Modificar una temporada por id inexistente
PUT http://localhost:3000/api/v1/seasons/7f972af8-cd33-49e8-8340-87cc37ef3476
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z",
    "fecha_fin": "2024-05-01T05:00:00.000Z",
    "id_cultivo": "c1234567-9abc-1234-5678-abc456789def",
    "novedades_id": "b1234567-8abc-1234-5678-abc456789def"
}
### Modificar una temporada por id con datos faltantes
PUT http://localhost:3000/api/v1/seasons/7f
Content-Type: application/json

{
    "nombre_temporada": "Temporada Fríjol 2024",
    "duracion": 120,
    "fecha_inicio": "2024-01-01T05:00:00.000Z"
}
